### ISSUE TITLE
CircleCI pack incomplete

### ISSUE THREAD

**Issue by humblearner** [StackStorm-Exchange/stackstorm-circle_ci#1]
`stackstorm-circle_ci`: missing all the basic pack folders: https://github.com/StackStorm/st2contrib/tree/master/packs/circle_ci

**Comment by emedvedev** [comment]
Thanks for looking into pack management :heart: The transfer is not final yet, we'll remove and re-create all the repos. Right now it's pre-populated to test things and figure out transfer/CI/install issues.
